---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
author: "Huilong"
date: "April 15, 2018"
---


## Loading and preprocessing the data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(lattice)
```

```{r}
setwd("C:/Users/u041383/Documents/Development/Data Science Course/5_Reproduce Approach")
path=getwd()
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
if (!file.exists(path)) {dir.create(path)}
download.file(url, file.path(path, "Data.zip"))

unzip(zipfile = "Data.zip")

act<-read.csv("activity.csv", header=T)

```

## What is mean total number of steps taken per day?
```{r}
act2 <- aggregate(steps ~ date, data = act, sum)

hist(act2$steps, breaks=10, col="red", main="Total steps taken per day", xlab="#Steps per day" )

mean(act2$steps)
median(act2$steps)

```
## What is the average daily activity pattern?
```{r}
act3 <- aggregate(steps ~ interval, data = act, sum)

plot(act3$interval, act3$steps, type="l", col="red", main="Average steps per period", 
     xlab="Interval", ylab="Avg. steps")

max_interval<-act3[which.max(act3$steps),1]

abline(v=835, lwd=2, col="blue")

```

The 5-minute interval containing the maximum number of steps is `r max_interval`.

## Imputing missing values
```{r}
sum(is.na(act$steps))

act_input<- transform(act, steps = ifelse(is.na(act$steps), act3$steps[match(act$interval, act3$interval)], act$steps))

sum(is.na(act_input$steps))

act_input2 <- aggregate(steps ~ date, data = act_input, sum)

hist(act_input2$steps, col="red", main="Total steps taken per day - Inputed", xlab="#Steps per day" )

mean(act_input2$steps)
median(act_input2$steps)

mean(act_input2$steps)-mean(act2$steps)
median(act_input2$steps)-median(act2$steps)
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
act_input[,2]<-as.Date(act_input$date)
act_wk<- mutate(act_input, day = ifelse(weekdays(act_input$date) == "Saturday" | weekdays(act_input$date) == "Sunday", "weekend", "weekday"))
act_wk$day<-as.factor(act_wk$day)
str(act_wk)

act_wk2 <- aggregate(steps ~ interval + day, act_wk, mean)


xyplot(steps ~ interval | day, data=act_wk2, layout=c(1,2), type="l", col="red", main="Average steps per period by weekend/weekday", 
     xlab="Interval", ylab="Avg. steps")


```




